export enum AuditAction {
  // Security
  LOGIN_SUCCESS = 'auth.login.success',
  LOGIN_FAILED = 'auth.login.failed',
  ROLE_CHANGED = 'admin.role.changed',
  ADMIN_DEACTIVATED = 'admin.deactivated',

  // Document
  RECORD_APPROVED = 'record.approved',
  RECORD_REJECTED = 'record.rejected',
  DOCUMENT_UPLOADED = 'document.uploaded',
  DOCUMENT_DELETED = 'document.deleted',
  DOCUMENT_VERIFIED = 'document.verified',
  DOCUMENT_REJECTED = 'document.rejected',
  DOCUMENT_ACCESSED = 'document.accessed', // who viewed a private doc + when
  DOCUMENT_REQUESTED = 'document.requested',
  DOCUMENT_REQUEST_FULFILLED = 'document.request.fulfilled',
  // Company
  COMPANY_CREATED = 'company.created',
  COMPANY_UPDATED = 'company.updated',
  COMPANY_FLAGGED = 'company.flagged',
  COMPANY_UNFLAGGED = 'company.unflagged',
  COMPANY_ARCHIVED = 'company.archived',
  COMPANY_UNARCHIVED = 'company.unarchived',
  COMPANY_SOFT_DELETED = 'company.soft_deleted',
  COMPANY_RESTORED = 'company.restored',
  COMPANY_VERIFIED = 'company.verified',
  COMPANY_VERIFICATION_UPDATED = 'company.verification.updated',
  COMPANY_LINK_UPDATED = 'company.link.updated',
  COMPANY_RELATIONSHIP_ADDED = 'company.relationship.added',
  COMPANY_RELATIONSHIP_UPDATED = 'company.relationship.updated',
  COMPANY_RELATIONSHIP_REMOVED = 'company.relationship.removed',
  // ─── Individual domain ───
  INDIVIDUAL_CREATED = 'individual.created',
  INDIVIDUAL_UPDATED = 'individual.updated',
  INDIVIDUAL_FLAGGED = 'individual.flagged',
  INDIVIDUAL_UNFLAGGED = 'individual.unflagged',
  INDIVIDUAL_ARCHIVED = 'individual.archived',
  INDIVIDUAL_UNARCHIVED = 'individual.unarchived',
  INDIVIDUAL_SOFT_DELETED = 'individual.soft_deleted',
  INDIVIDUAL_RESTORED = 'individual.restored',
  INDIVIDUAL_VERIFIED = 'individual.verified',
  PERSON_LINKED_TO_COMPANY = 'company.person.linked',
  PERSON_UNLINKED_FROM_COMPANY = 'company.person.unlinked',
  // ─── Redlist ───
  REDLIST_CASE_CREATED = 'redlist.case.created',
  REDLIST_CASE_UPDATED = 'redlist.case.updated',
  REDLIST_CASE_STATUS_CHANGED = 'redlist.case.status_changed',
  REDLIST_CASE_DELETED = 'redlist.case.deleted',
  REDLIST_ENTITY_LINKED = 'redlist.entity.linked',
  REDLIST_ENTITY_UNLINKED = 'redlist.entity.unlinked',
  REDLIST_EVIDENCE_ADDED = 'redlist.evidence.added',
  REDLIST_EVIDENCE_REMOVED = 'redlist.evidence.removed',
  REDLIST_EVIDENCE_ACCESSED = 'redlist.evidence.accessed',
  REDLIST_CASE_RESTORED = 'redlist.case.restored',
}
